apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  RENOVATE_REPOSITORIES: {{ .Values.repositories | quote }}
  RENOVATE_TOKEN: {{ .Values.renovateToken | quote }}
    # RENOVATE_GITHUB_COM_TOKEN: "your_github_com_token"
