apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  RENOVATE_REPOSITORIES: {{ .Values.repositories | quote }}
  RENOVATE_TOKEN: "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" 
  # RENOVATE_GITHUB_COM_TOKEN: "your_github_com_token"
