apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  # Example secrets for Renovate
  # RENOVATE_TOKEN: "your_github_token"
  # RENOVATE_PLATFORM: "github"
  # RENOVATE_GITHUB_COM_TOKEN: "your_github_com_token"
